"""Tabla items_conteo_inventario para cruce QMS/Defontana

Revision ID: 09d19df3f097
Revises: b0fd947e8683
Create Date: 2026-07-25 11:31:10.338010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d19df3f097'
down_revision = 'b0fd947e8683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_conteo_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('linea_negocio', sa.String(length=120), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('cantidad_qms', sa.Integer(), nullable=False),
    sa.Column('cantidad_defontana', sa.Integer(), nullable=False),
    sa.Column('cantidad_fisica', sa.Integer(), nullable=True),
    sa.Column('contado_por_id', sa.Integer(), nullable=True),
    sa.Column('contado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_conteo_empresa_codigo')
    )
    with op.batch_alter_table('items_conteo_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_conteo_inventario_codigo'), ['codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_conteo_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_conteo_inventario_codigo'))

    op.drop_table('items_conteo_inventario')
    # ### end Alembic commands ###
