"""Modulo de importaciones

Revision ID: 16135e017732
Revises: 99a787d146a7
Create Date: 2026-07-31 12:10:09.874145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16135e017732'
down_revision = '99a787d146a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('din_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('oc', sa.String(length=30), nullable=True),
    sa.Column('agencia', sa.String(length=100), nullable=True),
    sa.Column('n_doc_agencia', sa.String(length=30), nullable=True),
    sa.Column('monto_doc_agencia', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('n_invoice', sa.String(length=40), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('razon_social', sa.String(length=150), nullable=True),
    sa.Column('formulario', sa.String(length=10), nullable=True),
    sa.Column('folio', sa.String(length=30), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('vcto', sa.Date(), nullable=True),
    sa.Column('advalorem', sa.Integer(), nullable=False),
    sa.Column('total_pagado', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pei', sa.Date(), nullable=True),
    sa.Column('pei', sa.String(length=30), nullable=True),
    sa.Column('imp', sa.String(length=30), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=150), nullable=True),
    sa.Column('oc', sa.String(length=30), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('agencia', sa.String(length=100), nullable=True),
    sa.Column('tipo_saldo', sa.String(length=12), nullable=False),
    sa.Column('saldo_agencia', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('tratado_tlc', sa.String(length=10), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('costeo_valor', sa.Integer(), nullable=False),
    sa.Column('costeo_suma', sa.Integer(), nullable=False),
    sa.Column('costeo_diferencia', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores_importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('tratado_tlc', sa.String(length=10), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacion_asiento_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('tipo_doc', sa.String(length=30), nullable=True),
    sa.Column('n_doc', sa.String(length=30), nullable=True),
    sa.Column('cuenta', sa.String(length=120), nullable=True),
    sa.Column('debe', sa.Integer(), nullable=False),
    sa.Column('haber', sa.Integer(), nullable=False),
    sa.Column('ecomex', sa.Integer(), nullable=True),
    sa.Column('dif', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('cbte_linea', sa.String(length=30), nullable=True),
    sa.Column('n_cuenta', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['importacion_id'], ['importaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacion_grupo_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.Column('cbte', sa.String(length=30), nullable=True),
    sa.Column('saldo_anterior_monto', sa.Integer(), nullable=False),
    sa.Column('saldo_nuevo_tipo', sa.String(length=12), nullable=False),
    sa.Column('saldo_nuevo_cuenta', sa.String(length=120), nullable=True),
    sa.Column('saldo_nuevo_monto', sa.Integer(), nullable=False),
    sa.Column('monto_usd', sa.Float(), nullable=False),
    sa.Column('tipo_cambio', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('tipo_doc', sa.String(length=30), nullable=True),
    sa.Column('n_doc', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['importacion_id'], ['importaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('importacion_id', 'tipo', name='uq_importacion_grupo_meta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importacion_grupo_meta')
    op.drop_table('importacion_asiento_lineas')
    op.drop_table('proveedores_importacion')
    op.drop_table('importaciones')
    op.drop_table('din_registros')
    # ### end Alembic commands ###
