"""Esquema inicial

Revision ID: 1e2f5d1d3eb7
Revises: 
Create Date: 2026-07-24 16:01:18.802716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2f5d1d3eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=150), nullable=True),
    sa.Column('giro', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('comuna', sa.String(length=80), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('categorias_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('giro', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('comuna', sa.String(length=80), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('giro', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_modulo_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=30), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=False),
    sa.Column('puede_editar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'modulo', name='uq_rol_modulo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('activos_fijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_activo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('valor_compra', sa.Integer(), nullable=False),
    sa.Column('valor_residual', sa.Integer(), nullable=False),
    sa.Column('vida_util_meses', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('numero_factura_compra', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('motivo_baja', sa.String(length=255), nullable=True),
    sa.Column('es_arrendable', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_activo')
    )
    op.create_table('arriendos_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_activo', sa.String(length=255), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=False),
    sa.Column('monto_periodo', sa.Integer(), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('dias_alerta_vencimiento', sa.Integer(), nullable=False),
    sa.Column('ubicacion_uso', sa.String(length=150), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('terminado_manualmente', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('objeto', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('periodicidad_pago', sa.String(length=10), nullable=False),
    sa.Column('dias_alerta_vencimiento', sa.Integer(), nullable=False),
    sa.Column('usuario_responsable_id', sa.Integer(), nullable=True),
    sa.Column('contrato_anterior_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('terminado_manualmente', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_anterior_id'], ['contratos_cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=30), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=30), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=False),
    sa.Column('puede_editar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'modulo', name='uq_usuario_modulo')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('precio_costo', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_producto.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arriendos_salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('activo_fijo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino_prevista', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion_real', sa.Date(), nullable=True),
    sa.Column('monto_periodo', sa.Integer(), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('firma_cliente_nombre', sa.String(length=150), nullable=True),
    sa.Column('firma_cliente_ruta', sa.String(length=500), nullable=True),
    sa.Column('firma_cliente_en', sa.DateTime(), nullable=True),
    sa.Column('firma_cliente_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['activo_fijo_id'], ['activos_fijos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_arriendo_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arriendo_entrada_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha_pago_programada', sa.Date(), nullable=False),
    sa.Column('fecha_pago_real', sa.Date(), nullable=True),
    sa.Column('estado_pago', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['arriendo_entrada_id'], ['arriendos_entrada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturacion_arriendo_salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arriendo_salida_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('estado_pago', sa.String(length=10), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['arriendo_salida_id'], ['arriendos_salida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturacion_arriendo_salida')
    op.drop_table('pagos_arriendo_entrada')
    op.drop_table('movimientos_inventario')
    op.drop_table('arriendos_salida')
    op.drop_table('productos')
    op.drop_table('permisos_usuario')
    op.drop_table('documentos')
    op.drop_table('contratos_cliente')
    op.drop_table('arriendos_entrada')
    op.drop_table('activos_fijos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('rol_modulo_permiso')
    op.drop_table('proveedores')
    op.drop_table('clientes')
    op.drop_table('categorias_producto')
    op.drop_table('roles')
    op.drop_table('empresas')
    # ### end Alembic commands ###
