"""Une Control DIN al Costeo

Revision ID: 42648917363d
Revises: 8f641430669a
Create Date: 2026-08-02 05:51:50.810980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42648917363d'
down_revision = '8f641430669a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('din_agencia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('din_n_doc_agencia', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('din_monto_doc_agencia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('din_n_invoice', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('din_estado', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('din_rut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('din_razon_social', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('din_formulario', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('din_folio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('din_fecha_pago', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('din_vcto', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('din_advalorem_clp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('din_total_pagado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importaciones', schema=None) as batch_op:
        batch_op.drop_column('din_total_pagado')
        batch_op.drop_column('din_advalorem_clp')
        batch_op.drop_column('din_vcto')
        batch_op.drop_column('din_fecha_pago')
        batch_op.drop_column('din_folio')
        batch_op.drop_column('din_formulario')
        batch_op.drop_column('din_razon_social')
        batch_op.drop_column('din_rut')
        batch_op.drop_column('din_estado')
        batch_op.drop_column('din_n_invoice')
        batch_op.drop_column('din_monto_doc_agencia')
        batch_op.drop_column('din_n_doc_agencia')
        batch_op.drop_column('din_agencia')

    # ### end Alembic commands ###
