"""Tabla categorias_activo parametrizable

Revision ID: 52381036b6bf
Revises: 09d19df3f097
Create Date: 2026-07-25 11:55:54.173643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52381036b6bf'
down_revision = '09d19df3f097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_activo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_categoria_activo_nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias_activo')
    # ### end Alembic commands ###
