"""Estado y enlace de costeo con importacion

Revision ID: 8f641430669a
Revises: e3ab3e7463bd
Create Date: 2026-07-31 13:55:36.726040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f641430669a'
down_revision = 'e3ab3e7463bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importacion_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('estado', sa.String(length=15), nullable=False, server_default='en_proceso')
        )
        batch_op.create_foreign_key(
            'fk_costeo_importaciones_importacion_id', 'importaciones', ['importacion_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_costeo_importaciones_importacion_id', type_='foreignkey')
        batch_op.drop_column('estado')
        batch_op.drop_column('importacion_id')

    # ### end Alembic commands ###
