"""ad valorem opcional por producto en costeo

Revision ID: cbf67da9ab82
Revises: 42648917363d
Create Date: 2026-08-02 06:17:00.138082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf67da9ab82'
down_revision = '42648917363d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importacion_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiene_ad_valorem', sa.String(length=3), nullable=False, server_default='SI'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costeo_importacion_productos', schema=None) as batch_op:
        batch_op.drop_column('tiene_ad_valorem')

    # ### end Alembic commands ###
