"""Costeo detallado de importaciones

Revision ID: e3ab3e7463bd
Revises: 16135e017732
Create Date: 2026-07-31 13:17:06.012451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ab3e7463bd'
down_revision = '16135e017732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costeo_importaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('n_importacion', sa.String(length=30), nullable=True),
    sa.Column('fecha_llegada', sa.Date(), nullable=True),
    sa.Column('guia_despacho', sa.String(length=40), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('modo_venta', sa.String(length=40), nullable=True),
    sa.Column('purchase_order', sa.String(length=40), nullable=True),
    sa.Column('orden_trabajo', sa.String(length=60), nullable=True),
    sa.Column('responsable_costeo', sa.String(length=120), nullable=True),
    sa.Column('tipo_flete_proyectado', sa.String(length=20), nullable=True),
    sa.Column('solicitud_compra', sa.String(length=40), nullable=True),
    sa.Column('tasa_ad_valorem', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costeo_importacion_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costeo_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=6), nullable=False),
    sa.Column('nro_doc', sa.String(length=40), nullable=True),
    sa.Column('valor_tc', sa.Float(), nullable=True),
    sa.Column('valor_total_inv', sa.Float(), nullable=True),
    sa.Column('valor_clp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['costeo_id'], ['costeo_importaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('costeo_id', 'rol', name='uq_costeo_documento_rol')
    )
    op.create_table('costeo_importacion_gastos_internos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costeo_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nro_doc', sa.String(length=40), nullable=True),
    sa.Column('valor_clp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['costeo_id'], ['costeo_importaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('costeo_id', 'rol', name='uq_costeo_gasto_rol')
    )
    op.create_table('costeo_importacion_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costeo_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=200), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('valor_unitario_tc', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad_tc', sa.String(length=6), nullable=False),
    sa.Column('activo_fijo', sa.String(length=3), nullable=False),
    sa.Column('exw_moneda', sa.Float(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('exw_clp', sa.Integer(), nullable=False),
    sa.Column('crating_clp', sa.Integer(), nullable=False),
    sa.Column('flete_clp', sa.Integer(), nullable=False),
    sa.Column('seguro_clp', sa.Integer(), nullable=False),
    sa.Column('cif_clp', sa.Integer(), nullable=False),
    sa.Column('ad_valorem_clp', sa.Integer(), nullable=False),
    sa.Column('gastos_internos_clp', sa.Integer(), nullable=False),
    sa.Column('costo_total_clp', sa.Integer(), nullable=False),
    sa.Column('costo_unitario_inicial_clp', sa.Integer(), nullable=False),
    sa.Column('costo_unitario_final_clp', sa.Integer(), nullable=False),
    sa.Column('impacto_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['costeo_id'], ['costeo_importaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costeo_importacion_productos')
    op.drop_table('costeo_importacion_gastos_internos')
    op.drop_table('costeo_importacion_documentos')
    op.drop_table('costeo_importaciones')
    # ### end Alembic commands ###
