"""Tabla contratos_generados para plantilla de contrato de arriendo

Revision ID: ec63956c8313
Revises: 52381036b6bf
Create Date: 2026-07-25 14:17:56.135902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec63956c8313'
down_revision = '52381036b6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_contrato', sa.Date(), nullable=False),
    sa.Column('correo_arrendador', sa.String(length=120), nullable=True),
    sa.Column('representante_nombre', sa.String(length=150), nullable=False),
    sa.Column('representante_cedula', sa.String(length=15), nullable=False),
    sa.Column('arrendatario_domicilio', sa.String(length=255), nullable=False),
    sa.Column('arrendatario_correo', sa.String(length=120), nullable=False),
    sa.Column('fiador_tipo', sa.String(length=10), nullable=False),
    sa.Column('fiador_nombre', sa.String(length=150), nullable=False),
    sa.Column('fiador_rut', sa.String(length=15), nullable=False),
    sa.Column('fiador_domicilio', sa.String(length=255), nullable=True),
    sa.Column('fiador_correo', sa.String(length=120), nullable=True),
    sa.Column('fiador_representante', sa.String(length=150), nullable=True),
    sa.Column('cotizacion_numero', sa.String(length=30), nullable=False),
    sa.Column('cotizacion_fecha', sa.Date(), nullable=False),
    sa.Column('planta_ubicacion', sa.String(length=255), nullable=False),
    sa.Column('deducible_uf', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contratos_generados')
    # ### end Alembic commands ###
